[package]
name = "uengine_ecs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
uengine_cell = { path = "../cell" }
uengine_any = { path = "../any" }
uengine_utils = { path = "../utils" }
uengine_ecs_macros = { path = "macros" }
