[package]
name = "ueditor"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["rlib", "dylib"]

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
uengine = { path = "../engine" }
