[package]
name = "uengine_rendering"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
winit = "0.30.1"
# wgpu = "0.20.0"
uengine_core = { path = "../core" }
uengine_ecs = { path = "../ecs" }
